name: Deploy

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Move WebGL build
      run: cp -r src/pages/software-projects/Digital-Lancer-Tool/Digital\ Lancer\ Tool\ Build\ Web/Build dist/Build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: gwioninglasses-website
        path: ./dist/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'secrets'

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: gwioninglasses-website
        path: .
    
    
    - name: Delete old files
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: rm -r /var/www/gwioninglasses.com/html/*

    - name: Update production
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: gwioninglasses-website/*
        target: /var/www/gwioninglasses.com/html