name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment:
      name: 'secrets'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Move WebGL build
      run: cp -r src/pages/software-projects/Digital-Lancer-Tool/Digital\ Lancer\ Tool\ Build\ Web/Build dist/Build

    - name: Upload build to production
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: dist/*
        target: .

    - name: Delete old files
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          rm -r /var/www/gwioninglasses.com/html/* || true
          cp -r dist/* /var/www/gwioninglasses.com/html || true
          rm -r dist || true